### PR TITLE
fix firefly Flash update

### PR DESCRIPTION
**Pull request by rienafairefr**
as discussed, using the Zigduino model (stopping the serial redirection when flashing), it seems to work now :+1: 
Once merged I'll deploy the yocto image with the changes onto prod nodes ASAP.

### CODE REVIEW

**Comment by aabadie** [comment]
If everything goes like it should, I predict that the unit tests won't pass ;)

**Comment by aabadie** [comment]
But, in any case that's super nice that you have a fix for this :)

**Comment by aabadie** [comment]
hmm, it worked.

**Comment by rienafairefr** [comment]
If you want peace of mind of the test on CI node passing, I still need to understand why the /var/volatile fills up (nodes.test_gateway_code doesn't pass on my firefly in ci)

**Comment by aabadie** [comment]
maybe because your yocto image is quite old and the setup install some dependencies via pip. In newer images, all python dependencies are already provided by the yocto image.

**Comment by rienafairefr** [comment]
good idea. I'll check that

**Pull request merged**
